### ISSUE TITLE
brename can't find anything to rename

### ISSUE THREAD

**Issue by grmacman** [shenwei356/brename#11]
Hi,

i am trying to replace some special characters (: ; ? " \ / < > * |) from folder names on my Synology Diskstation.

Using the command <./brename -d -R -p ":" -r "_" /volume1/my_share> returns "0 path(s) to be renamed". I have tested searching for &,!,?,q,qh ... with the same result. (Searching for <?> returns <[ERRO] illegal regular expression for search pattern: ?>)

Why is brename not working for me? Is i possible to remove the given special characters with brename and how?

The directory tree was created, for testing purposes, with the following script

```
#!/bin/bash
# Decimal ASCII codes (see man ascii)
ARR=( {32..126} )

# Array count
arrcount=${#ARR[@]}

# return a random string
get_rand_dir(){
    for ((i=1; i<$((RANDOM%30)); i++)) {
        printf \\$(printf '%03o' ${ARR[RANDOM%arrcount]});
    }
}

dir=/volume1/my_share/

# appending random characters to make a hierarchy
for ((i=0; i<$((RANDOM%100)); i++)) {
    dir+="$(get_rand_dir)/"
}

echo $dir
mkdir -p "$dir"

oldir=$(echo "$dir" | cut -d '/' -f1-3)

while [[ $dir ]]; do
    dir=${dir%/*}
    cd $dir
    for ((i=0; i<$((RANDOM%100)); i++)) {
        mkdir &>/dev/null -p $(get_rand_dir)
    }
done

tree "$oldir"
```

![bildschirmfoto 2018-11-17 um 18 19 46](https://user-images.githubusercontent.com/45127991/48664018-b3f66c80-ea98-11e8-980e-256cbea52ba7.png)

**Comment by shenwei356** [comment]
brename -d -R -p ":" -r "_" /volume1/my_share -D

 help

    -D, --including-dir             rename directories
