### ISSUE TITLE
Please integrate with git

### ISSUE THREAD

**Issue by yurivict** [shenwei356/brename#20]
If renamed files are in the git repository, run ```git mv``` instead of just ```mv```.

```brename``` can auto-detect that (1) the ```git``` program is present (2) directory is inside of the git repository and (3) files are members of that repository. Then ```braneme``` should warn the user that it can either just rename files, or rename them as members of the git repository.

If ```-g``` (git integration) flag is given, ```brename``` would just run ```git mv``` on qualifying files.

**Comment by shenwei356** [comment]
We did not call shell `mv`.

For now, you may use a combination of `fd/find` + `parallel` + `git mv`.

**Comment by yurivict** [comment]
You can simply add an argument for "rename command".

For example, ```-c mv``` would be equivalent to the current behavior.
And ```-c 'git mv'``` would perform git-rename.
