### ISSUE TITLE
Does not rename or find directories with square brackets

### ISSUE THREAD

**Issue by sathishvj** [shenwei356/brename#21]
$ mkdir "abcd [efgh]"
$ brename -d -D -p "\[efgh\]" -r "" *
[INFO] 0 path(s) to be renamed

**Comment by shenwei356** [comment]
try 

    brename -d -D -p "\[efgh\]" -r "" *

**Comment by sathishvj** [comment]
My apologies for not mentioning it in the original post, but I had tried that also.  But it doesn't work.
fyi: I'm on a Mac and I tried these samples in the /tmp directory.

$ brename -d -D -p "\[efgh\]" -r "" *
[INFO] 0 path(s) to be renamed

**Comment by shenwei356** [comment]
I see, it's a tiny bug. `brename`  doe not rename the given root paths.

You can just remove the tailing `*`

    brename -d -D -p "\[efgh\]" -r ""
    [INFO] main options:
    [INFO]   ignore case: false
    [INFO]   search pattern: \[efgh\]
    [INFO]   include filters: .
    [INFO]   search paths: ./
    [INFO] 
    [INFO] checking: [ ok ] 'abcd [efgh]' -> 'abcd '
    [INFO] 1 path(s) to be renamed


Or use the patch:

- [brename_linux_amd64.tar.gz](https://github.com/shenwei356/brename/files/6986215/brename_linux_amd64.tar.gz)
- [brename_darwin_amd64.tar.gz](https://github.com/shenwei356/brename/files/6986214/brename_darwin_amd64.tar.gz)

It's fixed: 

    ./brename -d -D -p "\[efgh\]" -r "" *
    [INFO] main options:
    [INFO]   ignore case: false
    [INFO]   search pattern: \[efgh\]
    [INFO]   include filters: .
    [INFO]   search paths: abcd [efgh], binaries, brename, brename.go, CHANGES.md, generate-example-folder.sh, LICENSE, packaging.sh, README.md, screenshot
    [INFO] 
    [INFO] checking: [ ok ] 'abcd [efgh]/abcd [efgh].txt' -> 'abcd [efgh]/abcd .txt'
    [INFO] checking: [ ok ] 'abcd [efgh]/abcd [efgh]' -> 'abcd [efgh]/abcd '
    [INFO] checking: [ ok ] 'abcd [efgh]' -> 'abcd '
    [INFO] 3 path(s) to be renamed
