### ISSUE TITLE
Segmentation Fault upon execution in OpenBSD 6.9

### ISSUE THREAD

**Issue by anoduck** [shenwei356/brename#22]
Obviously, this is an extremely handy script that I have enjoyed using for years. Unfortunately, I have not used it lately. So, when I got back around to using it, I updated to the newest release and attempted a dry run:  

```shell
brename -p "\.php" -r "\.jpg" -d
[1]    35399 segmentation fault  /home/user/go/bin/brename -p "\.php" -r ".jpg" -d
```  

Then I tried to see what could have caused the issue and how to enable verbose output by accessing help:  

```shell
brename --help                  
[1]    84355 segmentation fault  /home/user/go/bin/brename --help

brename -h                  
[1]    84355 segmentation fault  /home/user/go/bin/brename -h
```

Even if I just enter the command `brename` the result is `31825 segmentation fault`. Not sure how to best approach troubleshooting this further. Let me know what else I can do or what other information I can provide to best assist in resolving this bug. 

I am currently running OpenBSD 6.9 with `go version go1.16.6 openbsd/amd64` in `zsh 5.8 (x86_64-unknown-openbsd6.9)`

**Comment by anoduck** [comment]
Still produces segmentation fault upon execution in OpenBSD 7.2.

Should it be assumed OpenBSD will not be supported?

**Comment by shenwei356** [comment]
how about compile from the source? 

```

wget https://go.dev/dl/go1.17.11.linux-amd64.tar.gz

tar -zxf go1.17.11.linux-amd64.tar.gz -C $HOME/

# or 
#   echo "export PATH=$PATH:$HOME/go/bin" >> ~/.bashrc
#   source ~/.bashrc
export PATH=$PATH:$HOME/go/bin

git clone https://github.com/shenwei356/brename
cd brename
go build

```

**Comment by anoduck** [comment]
Or, you could provide a totally awesome response... that works too... :)

On OpenBSD CURRENT (7.2), Go version is 1.18.4p1

Will build from source and see where that gets me.
