### ISSUE TITLE
Adding parental directory name to file names

### ISSUE THREAD

**Issue by vmikk** [shenwei356/brename#23]
Hello!
I'm trying to rename files adding their parent directory name as a prefix, however I can not succeed with `brename`.

Reproducible example:
```
mkdir -p Dir1
mkdir -p Dir2

touch Dir1/a.txt
touch Dir1/b.txt

touch Dir2/c.txt
touch Dir2/d.txt
```
```
├── Dir1
│   ├── a.txt
│   └── b.txt
└── Dir2
    ├── c.txt
    └── d.txt
```

I would like to add a name of parantal directory to each file.
The expected result is:
```
├── Dir1
│   ├── Dir1_a.txt
│   └── Dir1_b.txt
└── Dir2
    ├── Dir2_c.txt
    └── Dir2_d.txt
```

I've tried the following command, but it doesn't work:
```
brename \
  -p '(Dir[0-9])' \
  -r '$1/$1_' \
  -R -f '[a-z].txt' \
  -d
```

On Debian, it could be done with
```
rename 's/(.*)\//$1\/$1_/' */*
```
However, this command doesn't work on CentOS because it uses the other `rename` tool (from `util-linux` package).

Is it possible to perform this task with `brename`?

With kind regards,
Vladimir

**Comment by shenwei356** [comment]
[rush](https://github.com/shenwei356/rush), also one of my tools, can help.

```
tree
.
├── dir1
│   ├── a.txt
│   └── b.txt
└── dir2
    ├── c.txt
    └── d.txt
```


`rush`, likes `parallel`, has a placeholder `{%}` for the basename of a file.

```
# find directories and run `brename`.
find -type d | grep -v '^.$' \
    | rush 'cd {}; brename -R -p "^" -r {%}_'

```

The flag `-d` or `--dry-run` is recommended.

```
.
├── dir1
│   ├── .brename_detail.txt
│   ├── dir1_a.txt
│   └── dir1_b.txt
├── dir2
│   ├── .brename_detail.txt
│   ├── dir2_c.txt
│   └── dir2_d.txt
└── .directory

```

Delete `.brename_detail.txt` if you do not need them.

```
find -name ".brename_detail.txt" | rush 'rm {}'
```

**Comment by vmikk** [comment]
Hello!
Thank you so much, you've given really helpful idea (replacing the beginning of the line is very clever)!

With kind regards,
Vladimir
