### ISSUE TITLE
变量匹配问题

### ISSUE THREAD

**Issue by hx210** [shenwei356/brename#26]
问题格式匹配
```
(.*) - S(\d+)E(\d+)\.zh_(CN|TW).default.ass$
```
修改为
```
$1 - S$2E$3 - 第$3集.zh_$4.default.ass
```
替换为
```
brename -p '(.*) - S(\d+)E(\d+)\.zh_(CN|TW).default.ass$' -r '$1 - S$2E$3 - 第$3集.zh_$4.default.ass' -d
```
![图片](https://user-images.githubusercontent.com/76199340/195374116-31ac60e4-04b0-4e86-b7a2-689ef5974d0d.png)

预期中间像
S01E11 - 第11集

**Comment by shenwei356** [comment]
`第$3集`这里，`3`和`集`连在一起了，以为你说的是`3集`这个变量，得用 `${3}集`。同样，前面是`S${2}E${3}`。
