### ISSUE TITLE
Windows: brename doesn't detect when files will be overwritten if the replacement only differs in case

### ISSUE THREAD

**Issue by tspivey** [shenwei356/brename#28]
Using brename v2.12.0 on Windows.
Create two files, test.txt and test.doc.
```
brename -x -p "\..+$" -r "" -d

[INFO] checking: [ ok ] 'test.doc' -> 'test'
[ERRO] checking: [ overwriting newly renamed path ] 'test.txt' -> 'test'
[ERRO] 1 potential error(s) detected, please check
```

This works as expected. Now create test.txt and Test.doc.

```
brename -x -p "\..+$" -r "" -d

[INFO] checking: [ ok ] 'Test.doc' -> 'Test'
[INFO] checking: [ ok ] 'test.txt' -> 'test'
[INFO] 2 path(s) to be renamed
```

Now do the rename:
```
brename -x -p "\..+$" -r ""

[INFO] renamed: 'Test.doc' -> 'Test'
[INFO] renamed: 'test.txt' -> 'test'
[INFO] 2 path(s) renamed
```

Only one file remains in the directory, because NTFS is case insensitive.

**Comment by shenwei356** [comment]
Thanks for reporting, and I've added a flag `-w/--case-insensitive-path` for correctly checking file overwrites in file systems like NTFS (mostly in Windows). 

- [brename_windows_amd64.exe.tar.gz](https://github.com/shenwei356/brename/files/11035571/brename_windows_amd64.exe.tar.gz)
- [brename_linux_amd64.tar.gz](https://github.com/shenwei356/brename/files/11035570/brename_linux_amd64.tar.gz)

Right now, we show the warning message if it's not set in all operating systems. Should I make it on default for the Windows version?

```

$ brename -x -p "\..+$" -r "" -i -f ^Test -d
[INFO] main options:
[INFO]   ignore case: true
[INFO]   search pattern: (?i)\..+$
[INFO]      skip filters: ^\.
[INFO]   include filters: ^Test
[WARN] 
[WARN] If the file system where the search path locates is NTFS (mostly in Windows),
[WARN] please use -w/--case-insensitive-path to correctly check file overwrites!
[WARN] 
[INFO]   search paths: ./
[INFO] 
[INFO] checking: [ ok ] 'Test.doc' -> 'Test'
[INFO] checking: [ ok ] 'test.txt' -> 'test'
[INFO] 2 path(s) to be renamed

**Comment by shenwei356** [comment]
Hmm, I think it should be set by default on Windows.

![image](https://user-images.githubusercontent.com/2655946/226806628-da530d30-af79-4315-8cfc-967982afd492.png)

On Linux, we also show the warning message in case users are operating on an external disk with NTFS.


```
brename -x -p "\..+$" -r "" -i -f ^Test -d 
[WARN] 
[WARN] If the file system where the search path locates is NTFS (mostly on Windows),
[WARN] please use -w/--case-insensitive-path to correctly check file overwrites!
[WARN] 
[INFO] main options:
[INFO]   path filters and search pattern:
[INFO]         ignore case: true
[INFO]      search pattern: (?i)\..+$
[INFO]         replacement: 
[INFO] 
[INFO]        skip filters: ^\.
[INFO]     include filters: ^Test
[INFO] 
[INFO]   path overwrite checking:
[INFO]     case-insensitive path: false
[INFO]            overwrite mode: 0 (reporting error)
[INFO] 
[INFO] ------------------------------------------------------
[INFO] 
[INFO] search paths: ./
[INFO] 
[INFO] checking: [ ok ] 'Test.doc' -> 'Test'
[INFO] checking: [ ok ] 'test.txt' -> 'test'
[INFO] 2 path(s) to be renamed

```

**Comment by shenwei356** [comment]
For case 1, I also noticed the setting somewhere too.  As you said, it's an edge case. For most cases, we would better assume Windows users use case-intensive file systems. Then, for these professional users who can run tools like `fsutil`, we can offer another flag to disable the flag of `-w/--case-insensitive-path`, like `-W/--case-sensitive-path`.

For case 2, renaming `test.TXT` to `test.txt` should be stopped in case-sensitive filesystems when `text.txt` exists.

    [ERRO] checking: [ new path existed ] 'test.TXT' -> 'test.txt'

**Comment by shenwei356** [comment]
I've added the `-W/--case-sensitive-path` and  the case 2 is fixed. 

```
Warnings:
  1. The path in file systems like NTFS is case-insensitive, so you should switch on the flag
     -w/--case-insensitive-path to correctly check file overwrites.
  2. The flag -w/--case-insensitive-path is switched on by default on Windows, please use
     -W/--case-sensitive-path to disable it if the file system is indeed case sensitive.

Flags:
  -w, --case-insensitive-path     the file system (e.g., NTFS) is case-insensitive. It's automatically
                                  swiched on on Windows
  -W, --case-sensitive-path       believing that the file system is case-sensitive. Please use this to
                                  disable the flag -w/--case-insensitive-path, which is switched on by
                                  default on Windows

```

Here are some tests on Windows with two files (`test.TXT` and `Test.doc`) in one directory. The file system is ext2/ext3 according to the information from `stat -f`; actually, it's ext4.

####  test 1

![image](https://user-images.githubusercontent.com/2655946/227847851-f4834127-1e73-4f9d-96d1-675d885a5d4b.png)


Since it's ext4, I believe the paths should be case-sensitive, so I add `-W`.

![image](https://user-images.githubusercontent.com/2655946/227848220-d9ab8a6e-e00b-4c0c-bcaf-4437e9dd1f31.png)


#### test 2

![image](https://user-images.githubusercontent.com/2655946/227848015-dc2de0fa-4ed8-47f8-904e-0d92e1133b4a.png)

Please help to test it.

- [brename_darwin_amd64.tar.gz](https://github.com/shenwei356/brename/files/11074841/brename_darwin_amd64.tar.gz)
- [brename_linux_amd64.tar.gz](https://github.com/shenwei356/brename/files/11074843/brename_linux_amd64.tar.gz)
- [brename_windows_amd64.exe.tar.gz](https://github.com/shenwei356/brename/files/11074844/brename_windows_amd64.exe.tar.gz)

**Comment by shenwei356** [comment]
@tspivey I'll tag a new release if it works as expected :)

**Comment by tspivey** [comment]
I verified:
1. with test.txt and Test.doc, removing the extension fails because the files would conflict in case.
2. I could rename test.TXT to test.txt without problems.

I'm trying to come up with some edge cases reading the [official documentation](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file).

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

If I create `test.txt` and `test..txt`, then do:
```brename -p ".txt$" -r ""```
I'm left with `test`, and one of the files is lost.

**Comment by shenwei356** [comment]
> with test.txt and Test.doc, removing the extension fails because the files would conflict in case.

OK, it's exptected.

> I could rename test.TXT to test.txt without problems.

Cool.

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not.

🤮 Have to add another rule ...

**Comment by shenwei356** [comment]
> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not.

OK, they are not allowed now.

```
$ brename -p '.txt' -d
[ERRO] checking: [ new path ending with a period ] 'test..txt' -> 'test.'
[INFO] checking: [ ok ] 'test.txt' -> 'test'
[ERRO] 1 potential error(s) detected, please check
```

A warning message is added in the help message.

```
Warnings:
  1. The path in file systems like FAT32 or NTFS is case-insensitive, so you should switch on the flag
     -w/--case-insensitive-path to correctly check file overwrites.
  2. The flag -w/--case-insensitive-path is switched on by default on Windows, please use
     -W/--case-sensitive-path to disable it if the file system is indeed case-sensitive.
  3. New paths ending with a period of space, being error-prone, are not allowed.
```

[brename_windows_amd64.exe.tar.gz](https://github.com/shenwei356/brename/files/11143655/brename_windows_amd64.exe.tar.gz)
