### ISSUE TITLE
Underscore nullifies/ignored in replacement between matched groups

### ISSUE THREAD

**Issue by ammaraziz** [shenwei356/brename#34]
Hi Shenwei,

Thanks for the awesome. I came across a weird issue. I am trying to replace this pattern:

Input:
```
1234_OC43_S17_R1.fastq.gz
1234_OC43_S17_R2.fastq.gz
1235_OC43_S24_R1.fastq.gz
...
etc
```
Expected output:
```
S17_1234_OC43_R1.fastq.gz
S17_1234_OC43_R2.fastq.gz
S24_1235_OC43_R1.fastq.gz
...
etc
```
I want to move `S\d\d` pattern from the middle to the first of the string. eg this: `XXX_XXX_S17_R1.fastq.gz` becomes `S17_XXX_XXX_R1.fastq.gz`.

Command I used:

```
brename -p "(.*)_(S\d+)_(.*)" -r '$2_$1_$3' -d
```

Output:
```
  [OK] 1234_OC43_S17_R1.fastq.gz -> R1.fastq.gz
  [OK] 1234_OC43_S17_R2.fastq.gz  -> R2.fastq.gz
  [overwriting newly renamed path] 1235_OC43_S24_R1.fastq.gz -> R1.fastq.gz
```

Odd! `_` seems to completely nullify the group string eg `$1`

Replacing underscores with `-` fixes this issue:

```
brename -p "(.*)_(S\d+)_(.*)" -r '$2-$1-$3' -d
```

To me the issues seems to be replaced to the regex groups. Because when I run this to achieve the desired result it works:

```
brename -p "-" -r '_' -d
```

Thanks!

Versions:
```
brename v2.14.0
LSB Version:    core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID: Linuxmint
Description:    Linux Mint 21
Release:        21
Codename:       vanessa
```

**Comment by shenwei356** [comment]
It's a common issue. see https://github.com/shenwei356/brename/issues/33

**Comment by shenwei356** [comment]
No worries, it happens a lot. I really have to add this to attention or FAQs.

**Comment by ammaraziz** [comment]
Thank you @shenwei356 ! 

If I may offer a suggestion on the wording:

> Capture variables **better be** in the format of '${1}'.

`[it] better be` is an idiom in English that conveys an angry/threatening tone. I suggest changing the wording to something along the lines of: 

> Capture variables should be in the format of '${1}' to reduce errors

I hope you don't mind the correction.

Thank you again for taking the time to respond to my issue so quickly.

**Comment by shenwei356** [comment]
Thank you Ammar very much!
I never realized that, because the tones of these two phrases are reversed in Chinese ...
I'll change that.

**Comment by ammaraziz** [comment]
That's super interesting. I can see how the word 'should' can be a bit forward. 

I generally avoid the word as it's ambiguous but I couldn't think of another way to phrase it. 

Thanks again!

**Comment by shenwei356** [comment]
"recommended to be" might be a good alternative.
