### ISSUE TITLE
Add option to rename without touching file extension.

### ISSUE THREAD

**Issue by oltodosel** [shenwei356/brename#4]
So that these:
`brename -i -p ".+(S\d\dE\d\d).+mkv" -r '$1.mkv'`
`brename -i -p ".+(S\d\dE\d\d).+mp4" -r '$1.mp4'`
Could become this:
`brename --dont-touch-f-extensions -i -p ".+(S\d\dE\d\d).+" -r '$1'`

**Comment by shenwei356** [comment]
let me try

    brename -i -p ".+(S\d\dE\d\d).+([^\.]+)$" -r '$1.$2'

**Comment by shenwei356** [comment]
i'll add this option

**Comment by oltodosel** [comment]
I just thought it would've been good having such option, since mostly extensions aren't needed to be touched.
Your regexp isn't good.
[INFO] checking: [ ok ] 'Two.and.a.Half.Men.S02E01.Back.Off.Mary.Poppins.720p.WEB-DL.AAC2.0.H.264-MC.mkv' -> 'S02E01.v'

`brename -d -i -p ".+(S\d\dE\d\d).+\.(.+)$" -r '$1.$2'`

**Comment by shenwei356** [comment]
New option added:

```
  -e, --ignore-ext                    ignore file extension. i.e., replacement does not change file extension
```

Please help to test it. 

- [brename_darwin_amd64.tar.gz](https://github.com/shenwei356/brename/files/1202449/brename_darwin_amd64.tar.gz)
- [Uploading brename_linux_amd64.tar.gz…]()
- [brename_windows_amd64.exe.tar.gz](https://github.com/shenwei356/brename/files/1202451/brename_windows_amd64.exe.tar.gz)

```
$ brename -e -i -p ".+(S\d\dE\d\d).+" -r '$1' -d
[INFO] checking: [ ok ] 'Two.and.a.Half.Men.S02E01.Back.Off.Mary.Poppins.720p.WEB-DL.AAC2.0.H.264-MC.mkv' -> 'S02E01.mkv'
[INFO] 1 path(s) to be renamed
```

**Comment by shenwei356** [comment]
see [v2.3.0](https://github.com/shenwei356/brename/releases/tag/v2.3.0)
