### ISSUE TITLE
Skip errors

### ISSUE THREAD

**Issue by tspivey** [shenwei356/brename#6]
If I'm renaming a lot of files, I don't want a few errors to stop the process. I would like an option which just skips those renames, and continues renaming files.

**Comment by shenwei356** [comment]
What kind of errors to skip, show some examples please.

**Comment by shenwei356** [comment]
`brename` is use to safely renaming files, so it's designed to escaping any error.

**Comment by tspivey** [comment]
I would like to skip the errors about nonexistent files. For example, with these files:
```
01 Track 1.mp3
01_Track_1.mp3
02_Track_2.mp3
```

Running:
    brename -v2 -p '_' -r ' ' music

Produces this error:
```
[ERRO] checking: [ new path existed ] 'music/01_Track_1.mp3' -> 'music/01 Track 1.mp3'
[ERRO] 1 potential error(s) detected, please check
```

In this case, I would like an option to just rename what it can without overwriting the existing files.
At the end of this I would have:
```
01 Track 1.mp3
01_Track_1.mp3
02 Track 2.mp3
```
