### ISSUE TITLE
Supporting undo renames

### ISSUE THREAD

**Issue by shenwei356** [shenwei356/brename#8]
1. Saving renaming details of the **LAST** successful operation into current path, like `.brename_detail.txt`.
    1. We may not use `\t` as the delimiter cause it's legal in path name, `_shenwei356-brename_`  may better.
1. Running `brename -u` to read the file and reverse the renaming.
    1. Warning if the log file not existed.
    2. Reading and reversely renaming.
    3. Removing the log file.

**Comment by mo-han** [comment]
Please add an option to disable undo, otherwise I need to do an extra step to delete the `.brename_detail.txt` file

**Comment by shenwei356** [comment]
Safety is the priority of `brename`. 

An environment variable could be a good way.

    BRENAME_DISABLE_UNDO

**Comment by sergeevabc** [comment]
Dear @shenwei356, creating environment variables is not a portable way to do things. Also the constant fear of doing something wrong is an constant obstacle to grow. It should not should not stand in the way of the advanced user's need to complete a well-defined task. 

So please consider adding a couple of switches to mitigate long-irritating features of Brename:
* include objects starting with dot (e.g. I maintain tags that way and sometimes need to change them C:\DOCS\.tags1 secret internal public -> rename _secret_ into _confidential_)
* disable undo not to delete .brename_detail.txt now and then, because it's a _pain_

**Comment by shenwei356** [comment]
Here's my plan:

> disable creating .brename_detail.txt

1. add a new flag to recursively remove all `.brename_detail.txt` files in the current or given directory.
2. add a new flag to disable creating `creating .brename_detail.txt` files.

> include objects starting with dot

1. add a new option to set an excluding filter, similar to `-F, --exclude-filters`. Adding an extra filter is for backward compatibility

**Comment by shenwei356** [comment]
Implemented. Please have a try.

- [brename_windows_amd64.exe.tar.gz](https://github.com/shenwei356/brename/files/10082190/brename_windows_amd64.exe.tar.gz)

Added examples:

```
  11. disable undo if you do not want to create .brename_detail.txt (-x)
      brename -p xxx -r yyy -x
  12. clear/remove all .brename_detail.txt files (--clear)
      brename --clear -R
  13. also operate on hidden files: empty -S (default: ^\.)
      brename -p xxx -r yyy -S ""
```

New options

```
      --clear                     remove all .brename_detail.txt" file,  you may need to add
                                  -R/--recursive to recursively clear all files in the given path
  -x, --disable-undo              do not create .brename_detail.txt file for undo
  -S, --skip-filters strings      skip file filter(s) (regular expression, NOT wildcard). multiple
                                  values supported, e.g., -S "^\." for skipping files starting with a
                                  dot, but ATTENTION: each comma in the filter is treated as the
                                  separator of multiple filters, please use double quotation marks for
                                  patterns containing comma, e.g., -p '"A{2,}" (default [^\.])
```

**Comment by sergeevabc** [comment]
@shenwei356, I'm relieved to hear that you agreed to implement the requested features for advanced users so quickly. It did feel as though a weight had been lifted off my mind. Happily renaming folders throughout today.

**Comment by shenwei356** [comment]
Cheers! If no error or bug is found, I'll release the new version the next day.

**Comment by shenwei356** [comment]
It's available here: https://github.com/shenwei356/brename/releases/tag/v2.12.0
